In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os.path
import sys
import django
sys.path.append('/home/galm/software/django/tmv/BasicBrowser')
sys.path.append('/home/max/software/django-tmv/tmv_mcc-apsis/BasicBrowser')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "BasicBrowser.settings")
django.setup()
from scoping.models import *

,Article ID,User Name,Resolve?,Include,0.1 Coder initials,0.2 Summarize,0.3 Sufficiency,1.1 Geography,"1.1.1 Geography (country, if any)",1.2 Sector,...,6.4.1 Approach limits,6.4.2 Approach limits (JUSTIFY),7.1 Methods,7.2 Coherence,7.3 Adequacy,7.4 Relevance,User Note,Title,Journal,Authors
0,8518313,leaberrang,NaN,False,LBF,not relevant,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Evaluation and breeding of tedera for Mediterr...,Crop and Pasture Science,"Real, D.; Oldham, C.M.; Nelson, M.N.; Croser, ..."
1,8518313,austinstephaniee,NaN,False,SA,Exclusion: the article focusses on plant breed...,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Evaluation and breeding of tedera for Mediterr...,Crop and Pasture Science,"Real, D.; Oldham, C.M.; Nelson, M.N.; Croser, ..."
2,8520105,alexandra.lesnikowski,NaN,True,AL,This article looks at irrigation adaptation st...,True,Africa,Tunisia,Food fibre & other ecosystem products||| Wate...,...,No,NaN,Methods seem robust and appropriate to the emp...,There is vagueness around questions about the ...,Methods appear adequate. Survey covered 190 fa...,Relevant to areas experiencing desertification...,NaN,Water and climate change: What are the adaptat...,New Medit,"Mahdhi, N.; Sghaier, M.; Fouzai, A.; Kadri, N."
3,8520106,alexandra.lesnikowski,NaN,True,AL,This article examines emerging adaptations str...,True,Africa,"Cameroon, Nigeria, Chad, Niger",Terrestrial & freshwater ecosystems||| Water ...,...,N/A,NaN,Methods seem sufficient- data integrates both ...,Unclear whether most of the adaptation strateg...,Limited detail on adaptation implementation.,Relevant to freshwater ecosystem areas facing ...,NaN,Perception of climate change and local practic...,Geo-Eco-Trop,"Sambo, A."
4,8520107,l.berrangford,NaN,False,LBF,"while a very interesting article, it does not ...",False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adaptation and international climate policy,Wiley Interdisciplinary Reviews: Climate Change,"Khan, M.R.; Roberts, J.T."

In [23]:
# Load the data and match to the APSIS database

django.db.connection.close()
get_abstracts = False
if get_abstracts:
    df = pd.read_excel("data/GAMI_MasterData_5August2020.xlsx")
    df["content"] = np.NaN
    df['APSIS ID'] = None
    for i,row in df.iterrows():
        t = row['Title'].replace('Ã\x82Â\xa0','').replace('Ã¢â\x82¬â\x80\x9c','').replace('Ã\x83Â¢','').replace('â€™','')
        t = t.replace('Ã§','ç').replace('â€˜','').replace('â€”','')
        try:
            d = Doc.objects.get(tslug=Doc.make_tslug(t), query=8843)
        except:
            try:
                d = Doc.objects.get(tslug=Doc.make_tslug(t))
            except:
                d = Doc.objects.filter(tslug=Doc.make_tslug(t)).first()
        if d is None:
            d = Doc.objects.filter(tslug__unaccent=Doc.make_tslug(t)).first()
        if d is None:
            d = Doc.objects.filter(tslug__contains=Doc.make_tslug(t[:100])).first()
        if d is None:
            d = Doc.objects.filter(tslug__contains=Doc.make_tslug(t[:45])).first()
        if "hitherto neglected gender-sensitive public health perspective" in t:
            d = Doc.objects.filter(tslug__contains=Doc.make_tslug("hitherto neglected gender-sensitive public health perspective")).first()
        if "Seaweed (Mwani) farming" in t:
            d = Doc.objects.filter(tslug__contains=Doc.make_tslug("Seaweed (Mwani) farming")).first()
        if d is None:
            d = Doc.objects.filter(tslug__contains=Doc.make_tslug(t[15:])).first()
        if d is None:
            d = Doc.objects.filter(tslug__contains=Doc.make_tslug(t[35:])).first()
        if "Sistemas agroflorestais como estrategia" in t:
            d = Doc.objects.get(tslug='sistemasagroflorestaiscomoestratégiadeadaptaçãoaosdesafiosdasmudançasclimáticasnobrasil')
        #print(d.title)
        if d is None:
            print(t)
            continue
        df.loc[i, "APSIS ID"] = d.pk
        df.loc[i, "content"] = d.content
    df.to_csv('data/GAMI_master_titles.csv',index=False)
else:
    df = pd.read_csv('data/GAMI_master_titles.csv')
    df = df[pd.notna(df['APSIS ID'])]
df.head()

,Article ID,User Name,Resolve?,Include,0.1 Coder initials,0.2 Summarize,0.3 Sufficiency,1.1 Geography,"1.1.1 Geography (country, if any)",1.2 Sector,...,7.1 Methods,7.2 Coherence,7.3 Adequacy,7.4 Relevance,User Note,Title,Journal,Authors,content,APSIS ID
0,8518313,leaberrang,NaN,False,LBF,not relevant,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Evaluation and breeding of tedera for Mediterr...,Crop and Pasture Science,"Real, D.; Oldham, C.M.; Nelson, M.N.; Croser, ...",Tedera (Bituminaria bituminosa C.H. Stirton va...,1486801.0
1,8518313,austinstephaniee,NaN,False,SA,Exclusion: the article focusses on plant breed...,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Evaluation and breeding of tedera for Mediterr...,Crop and Pasture Science,"Real, D.; Oldham, C.M.; Nelson, M.N.; Croser, ...",Tedera (Bituminaria bituminosa C.H. Stirton va...,1486801.0
3,8520106,alexandra.lesnikowski,NaN,True,AL,This article examines emerging adaptations str...,True,Africa,"Cameroon, Nigeria, Chad, Niger",Terrestrial & freshwater ecosystems||| Water ...,...,Methods seem sufficient- data integrates both ...,Unclear whether most of the adaptation strateg...,Limited detail on adaptation implementation.,Relevant to freshwater ecosystem areas facing ...,NaN,Perception of climate change and local practic...,Geo-Eco-Trop,"Sambo, A.","Lake Chad, the main water source in Central Af...",541027.0
4,8520107,l.berrangford,NaN,False,LBF,"while a very interesting article, it does not ...",False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Adaptation and international climate policy,Wiley Interdisciplinary Reviews: Climate Change,"Khan, M.R.; Roberts, J.T.",Because of the failure of the world to agree a...,19175.0
5,8520108,carolzavaleta2009,NaN,True,cz,"""This article examined obstacles and opportuni...",True,Central and South America||| North America,Peru|||Chile|||MÃ©xico,Cities settlements & key infrastructure,...,"Interviews of key stakeholders, including poli...","No, this articule was mostly focus on understa...","Three countries seems important scope, but the...",For Latin American MegaCities,NaN,Opportunities and barriers for urban adaptatio...,Eure,"Schaller, S.; Jean-Baptiste, N.; Lehmann, P.",This paper analyzes opportunities and barriers...,364963.0

In [34]:
# Filter out only the included studies

df = df[df['Include']==True]
print(df['APSIS ID'].unique().shape)
df.head()

(1807,)

,Article ID,User Name,Resolve?,Include,0.1 Coder initials,0.2 Summarize,0.3 Sufficiency,1.1 Geography,"1.1.1 Geography (country, if any)",1.2 Sector,...,7.1 Methods,7.2 Coherence,7.3 Adequacy,7.4 Relevance,User Note,Title,Journal,Authors,content,APSIS ID
3,8520106,alexandra.lesnikowski,NaN,True,AL,This article examines emerging adaptations str...,True,Africa,"Cameroon, Nigeria, Chad, Niger",Terrestrial & freshwater ecosystems||| Water ...,...,Methods seem sufficient- data integrates both ...,Unclear whether most of the adaptation strateg...,Limited detail on adaptation implementation.,Relevant to freshwater ecosystem areas facing ...,NaN,Perception of climate change and local practic...,Geo-Eco-Trop,"Sambo, A.","Lake Chad, the main water source in Central Af...",541027.0
5,8520108,carolzavaleta2009,NaN,True,cz,"""This article examined obstacles and opportuni...",True,Central and South America||| North America,Peru|||Chile|||MÃ©xico,Cities settlements & key infrastructure,...,"Interviews of key stakeholders, including poli...","No, this articule was mostly focus on understa...","Three countries seems important scope, but the...",For Latin American MegaCities,NaN,Opportunities and barriers for urban adaptatio...,Eure,"Schaller, S.; Jean-Baptiste, N.; Lehmann, P.",This paper analyzes opportunities and barriers...,364963.0
13,8520112,b.vanbavel1,NaN,True,BvB,"By engaging in a civil society organization, f...",True,Central and South America,"Cuenca RÃ­o Las Piedras, Colombia",Terrestrial & freshwater ecosystems||| Food f...,...,"yes, bias towards only qualitative data. ""All ...",it was unclear sometimes how the response acti...,very small number of fincas (10/64) in the ass...,"authors claim findings to be transferrable ""Co...",NaN,"The Biosphere Reserve Andean Belt, Colombia. A...",Revista de Geografia Norte Grande,"Borsdorf, A.; Mergili, M.; Ortega, L.A.",The Río Las Piedras basin in the Biosphere Res...,543992.0
14,8520113,dorothy.heinrich,NaN,True,DH,This article examines the impacts of inter-ann...,True,Africa,Algeria,Terrestrial & freshwater ecosystems||| Povert...,...,Yes,Yes,Small sample size but two communities for cros...,Context-specific but study could likely be rep...,NaN,Adaptation to drought in the algerian steppe: ...,Cahiers Agricultures,"Daoudi, A.; Terranti, S.; Hammouda, R.F.; BÃ©d...","Inter-annual variability, which characterizes ...",345380.0
15,8520114,yuanyuan.shang,NaN,True,YS,This paper explores the structural differences...,True,Asia,China,Food fibre & other ecosystem products,...,"Yes. The authors conducted survey, and used pa...",No. The adaptation part is relatively short an...,"The sample sizes are relatively small, and the...","Yes, this is a case study of two villages in C...",NaN,Rural household perceptions and adaptations to...,Shengtai Xuebao/ Acta Ecologica Sinica,"Qi, X.H.; Yang, Y.; Jin, X.X.; Liu, G.Q.; Da L...",The negative impact of climate change on rural...,855871.0

In [242]:
# Make a table to show which documents were coded by whom
df['coded'] = 1
df['CI'] = df['0.1 Coder initials'].str.strip()#.str[0].str.lower() # < uncomment if we want to group together coders with the same first initial
pair_lookup = df[['APSIS ID','CI','coded']].pivot_table(index="APSIS ID",columns="CI").fillna(0)

pair_lookup

          coded                                                  ...       \
CI         A.M. A.T.Z A.T.Z.  ACS  ADF   AF   AG   AH   AL   AM  ...  kds
APSIS ID                                                         ...
1.0         0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
3527.0      0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
4201.0      0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
5563.0      0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
5789.0      0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
...         ...   ...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3806673.0   0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
3806822.0   0.0   0.0    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0
3810032.0   0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
3814788.0   0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0
3822184.0   0.0   0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0

                                                                        \
CI        khavhagalivp pamul pkb911 pratik shukla sitatiasha  sjd   so
APSIS ID
1.0                0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
3527.0             0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
4201.0             1.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
5563.0             0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
5789.0             0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
...                ...   ...    ...    ...    ...        ...  ...  ...
3806673.0          0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
3806822.0          0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
3810032.0          0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
3814788.0          0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0
3822184.0          0.0   0.0    0.0    0.0    0.0        0.0  0.0  0.0


CI        villaverdeivan
APSIS ID
1.0                  0.0
3527.0               0.0
4201.0               0.0
5563.0               0.0
5789.0               0.0
...                  ...
3806673.0            0.0
3806822.0            0.0
3810032.0            0.0
3814788.0            0.0
3822184.0            0.0

[1807 rows x 155 columns]

In [247]:
# Get the combinations of pairs and count how many documents they coded together

pairs = []
combinations = []
for name, group in df[['APSIS ID','CI']].groupby("APSIS ID")['CI']:#.aggregate(lambda x: ', '.join(x))#.to_frame()
    if len(set([x.strip() for x in group])) > 1:   
        for p in itertools.combinations(group,2):
            if set(p) in combinations:
                continue
            if p[0]==p[1]:
                continue
            combinations.append(set(p))
            pp = pair_lookup[(pair_lookup[('coded',p[0])]==1) & (pair_lookup[('coded',p[1])]==1)]
            n = pp.shape[0]
            if n > 0:
                x = {"p0": p[0], "p1": p[1], "n": n}
                pairs.append(x)
len(pairs)
    
#pair_lookup

1716

In [248]:
# How many documents have each pair coded?
pair_df = pd.DataFrame.from_dict(pairs)
pair_df.sort_values('n',ascending=False)

                 p0   p1   n
99               MA   DD  40
120             ARS   SB  28
92               DC   ET  25
175              KB   KJ  24
20               EG  RRH  23
...             ...  ...  ..
960              DC   MA   1
961              DC   NC   1
230   Jordi Sardans   TH   1
963              SK   DD   1
1715            CAG   MS   1

[1716 rows x 3 columns]

In [249]:
# Load the master data

master_df = pd.read_csv('data/GAMI_Database_with_bibinfo.csv')
print(master_df.shape)
master_df = master_df.merge(df[~df.duplicated(["APSIS ID","content"])][["APSIS ID", "content"]],how="left")

columns = ["APSIS ID","Title","content"]
y_column = "1.2.Sector"

# This is a function than turns a column with multiple values separated by "|||" into separate binary columns

def widen_column(df, column, sep='|||'):
    columns = set([])
    for x in df[column].unique():
        for s in str(x).split(sep):
            s = s.strip()
            if s =="nan" or s=="None" or s=="" or s is None or "no information" in s.lower() or s=="Other":
                continue
            columns.add(s.strip())
            
    for c in columns:
        print(repr(c))
        df[c] = 0
        df.loc[df[column].str.contains(c)==True,c] = 1
        
    return df, columns

# Remove some typos
master_df['GEOG_REGION'] = master_df['GEOG_REGION'].str.replace('IslandsEurope', 'Islands|Europe')
master_df['GEOG_REGION'] = master_df['GEOG_REGION'].str.replace('AmericaAfrica', 'America|Africa')
master_df['1.2.Sector'] = master_df['1.2.Sector'].str.replace('Health Health', 'Health')
            
# Run the widen column function on sectors, topics, actors, etc.
print("SECTORS\n")
master_df, sectors = widen_column(master_df, '1.2.Sector')

print("\nTOPICS\n")
master_df, topics = widen_column(master_df, '1.3.Cross.cutting.topics')

print("\nACTORS\n")
master_df, actors = widen_column(master_df, '2.1.1.Actors.Institutions', '|')

print("\nREGIONS\n")
master_df, regions = widen_column(master_df, 'GEOG_REGION', '|')
    
print("\nHAZARDS\n")
master_df, hazards = widen_column(master_df, '3.3.1.Hazards', '|')
    
master_df.head()


master_df = master_df[(pd.notna(master_df['APSIS ID']))].reset_index(drop=True)
master_df

(1682, 110)
SECTORS

'Food fibre & other ecosystem products'
'Health, well-being & communities'
'Terrestrial & freshwater ecosystems'
'Poverty livelihoods & sustainable development'
'Ocean & coastal ecosystems'
'Cities settlements & key infrastructure'
'Water & sanitation'

TOPICS

'Deserts/semi-arid areas/desertification'
'Mediterranean'
'Cities and settlements by the sea'
'Biodiversity hotspots'
'Tropic forests'
'Polar regions'
'Mountains'

ACTORS

'Private sector corporations'
'Civil Society- international/multinational/national'
'Private sector SMEs'
'National government'
'Individuals or households'
'Local government'
'International or multinational governance institutions'
'Civil Society- sub-national or local'
'Sub-national government'

REGIONS

'North America'
'Australia'
'Central & South America'
'Islands'
'Africa'
'Asia'
'Europe'

HAZARDS

'General climate impacts'
'Precipitation variability'
'Extreme precipitation and inland flooding'
'Rising ocean temperature and ocean acidification'
'Sea level rise'
'Drought'
'Increased frequency and intensity of extreme heat'
'Loss of Arctic sea ice'

,Article.ID,Summarize,1.1.Geography,GEOG_REGION,1.1.1.Geography-Country,1.2.Sector,1.3.Cross.cutting.topics,1.4.Indigenous.knowledge,1.5.Local.knowledge,2.1.1.Actors.Institutions,...,Asia,Europe,General climate impacts,Precipitation variability,Extreme precipitation and inland flooding,Rising ocean temperature and ocean acidification,Sea level rise,Drought,Increased frequency and intensity of extreme heat,Loss of Arctic sea ice
0,6205478,The study documents the effect of human capita...,Africa,Africa|,Bawku West district located in the north-easte...,Poverty livelihoods & sustainable development,Deserts/semi-arid areas/desertification,False,False,Individuals or households||| Local government,...,0,0,1,1,0,0,0,1,0,0
1,6205479,he aim of this study was to understand how fam...,Africa,Africa|,Tunisia,Food fibre & other ecosystem products|||Healt...,Biodiversity hotspots,True,True,Civil Society- sub-national or local||| Indiv...,...,0,0,1,0,0,0,0,0,0,0
2,6205480,This study assessed the influence of climate v...,Africa,Africa|,Tanzania,Poverty livelihoods & sustainable development,None,False,False,Individuals or households,...,0,0,0,0,1,0,0,1,0,0
3,6205481,the study evaluates cropping adaptation option...,Africa,Africa|,"Zimbabwe|||Samburu County, Kenya",Poverty livelihoods & sustainable development,None,False,False,Individuals or households,...,0,0,1,1,1,0,0,1,0,0
4,6205482,Using field-based data collected from two stud...,Africa,Africa|Europe,Mukonchi and Lunchu settlements in Central Pro...,"Health, well-being & communities",Deserts/semi-arid areas/desertification,False,False,Individuals or households,...,0,1,1,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,8535751,This article includes two case studies of how ...,Asia,|Asia|,Nepal,Terrestrial & freshwater ecosystems||| Food f...,NaN,False,False,Individuals or households,...,1,0,0,1,0,0,0,0,0,0
1676,8535752,This study focuses on how people adapt to cor...,Asia,|Asia|,Indonesia,Ocean & coastal ecosystems||| Food fibre & ot...,Cities and settlements by the sea,False,False,Individuals or households,...,1,0,0,0,0,1,0,0,0,0
1677,8535781,Smallholder mixed-farming systems in Nepal are...,Asia,|Asia|,Nepal,Terrestrial & freshwater ecosystems||| Water ...,Mountains,False,True,Individuals or households,...,1,0,1,1,0,0,0,1,1,0
1678,8535786,The study employs a cross-sectional survey to ...,Africa,Africa|,Ethiopia (sub-Afroalpine to Afroalpine)|||Ethi...,Food fibre & other ecosystem products||| Pove...,Mountains||| Deserts/semi-arid areas/desertif...,False,False,Individuals or households||| Local government,...,0,0,1,1,0,0,0,1,0,0
1679,8535788,"""This study empirically assesses the impacts o...",Asia,|Asia|,Bangladesh|||Bangladesh (Manikganj District),Terrestrial & freshwater ecosystems||| Water ...,Cities and settlements by the sea||| Biodive...,False,False,Individuals or households||| Other||| Local g...,...,1,0,1,1,0,0,0,1,0,0

In [250]:
# y is the variable (in this case a matrix of 1s and 0s as wide as the number of sectors and as long as the )
master_df['labels'] = list(master_df[sectors].values)
y = np.matrix(master_df[sectors])

In [251]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier


pipeline = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', OneVsRestClassifier(SVC(probability=True))),
])

parameters = [
    {
        'vect__max_df': (0.75,),
        'vect__min_df': (2, 5),
        'vect__ngram_range': ((1, 2),),  
        'clf__estimator__kernel': ['rbf'], 
        'clf__estimator__gamma': [1e-3, 1e-4],
        'clf__estimator__C': [100, 1000],
        'clf__estimator__class_weight': ['balanced',]
    },
    {
        'vect__max_df': (0.75,),
        'vect__min_df': (2, 5),
        'vect__ngram_range': ((1, 2),),  
        'clf__estimator__kernel': ['linear'], 
        'clf__estimator__C': [1, 10],
        'clf__estimator__class_weight': ['balanced',]
    }
]

grid_search = GridSearchCV(pipeline, parameters, n_jobs=6, verbose=1, scoring="f1_macro")

In [255]:
for i, row in pair_df.sort_values('n',ascending=False).iterrows():    
    ids = pair_lookup[(pair_lookup[('coded',row["p0"])]==1) & (pair_lookup[('coded',row["p1"])]==1)].index
    test = master_df[master_df['APSIS ID'].isin(ids)].index
    train = master_df[~master_df['APSIS ID'].isin(ids)].index
    
    grid_search.fit(master_df.loc[train, 'content'].astype(str), y[train])
    
    y_pred = grid_search.predict_proba(master_df.loc[test,'content'])
    
    preds = pd.DataFrame(y_pred)
    preds.columns = sectors
    preds["APSIS ID"] = list(master_df.loc[test]["APSIS ID"])
    preds["Title"] = list(master_df.loc[test]["Title"])
    
    preds.to_csv(f'results/preds_{row["p0"]}_{row["p1"]}_sector.csv',index=False)
    
    break
    
preds.head()

,Food fibre & other ecosystem products,"Health, well-being & communities",Terrestrial & freshwater ecosystems,Poverty livelihoods & sustainable development,Ocean & coastal ecosystems,Cities settlements & key infrastructure,Water & sanitation,APSIS ID,Title
0,0.090156,0.490751,0.094702,0.283559,0.076649,0.865121,0.323589,1622603.0,Mitigating Climate Change Related Floods in Ur...
1,0.441489,0.415611,0.063092,0.433815,0.043139,0.241533,0.113166,1280970.0,Responses to Climate Variability in Urban Poor...
2,0.304986,0.323382,0.118941,0.236543,0.064025,0.382411,0.150918,129652.0,On the predicted effectiveness of climate adap...
3,0.080018,0.480596,0.098437,0.257106,0.261059,0.675324,0.263258,554420.0,Urban planning and sustainable adaptation to s...
4,0.414201,0.356473,0.172858,0.289731,0.074927,0.097520,0.258485,441108.0,Corporate Adaptation Behaviour to Deal With Cl...

In [ ]:
# We can also see how the different model candidates performed
results = pd.DataFrame(grid_search.cv_results_)
results.sort_values('mean_test_score',ascending=False).head()

In [265]:
from sklearn.model_selection import KFold

# Now we just split into 5 test sets, and for each of these make a prediction based on the rest of the data
predictions = master_df[['Title','content']]
kf = KFold(n_splits=5, shuffle=True)
for train, test in kf.split(master_df.index):
    grid_search = GridSearchCV(pipeline, parameters, n_jobs=8, verbose=1, scoring="f1_macro")
    grid_search.fit(master_df.loc[train, 'content'].astype(str), y[train])
    print("best macro f1 score: ", grid_search.best_score_)
    y_pred = grid_search.predict_proba(master_df.loc[test,'content'].astype(str))
    for i, t in enumerate(sectors):
        predictions.loc[test,t] = y_pred[:,i]
        
predictions.head()

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed: 10.7min
[Parallel(n_jobs=8)]: Done  60 out of  60 | elapsed: 16.8min finished

best macro f1 score:  0.49730211816491965

/home/max/software/django-tmv/tmv/venv/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/max/software/django-tmv/tmv/venv/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed: 11.5min
[Parallel(n_jobs=8)]: Done  60 out of  60 | elapsed: 17.6min finished

best macro f1 score:  0.48632632047341834

/home/max/software/django-tmv/tmv/venv/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed: 11.4min
[Parallel(n_jobs=8)]: Done  60 out of  60 | elapsed: 17.8min finished

best macro f1 score:  0.5077570455066878

/home/max/software/django-tmv/tmv/venv/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed: 12.9min
[Parallel(n_jobs=8)]: Done  60 out of  60 | elapsed: 21.0min finished

best macro f1 score:  0.4792489245855215

/home/max/software/django-tmv/tmv/venv/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed: 15.5min
[Parallel(n_jobs=8)]: Done  60 out of  60 | elapsed: 23.4min finished

best macro f1 score:  0.49411079476320935

/home/max/software/django-tmv/tmv/venv/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

,Title,content,Food fibre & other ecosystem products,"Health, well-being & communities",Terrestrial & freshwater ecosystems,Poverty livelihoods & sustainable development,Ocean & coastal ecosystems,Cities settlements & key infrastructure,Water & sanitation
0,The response to climate variability among farm...,This study examines the effect of human capita...,0.888327,0.223000,0.071591,0.565519,0.037325,0.037760,0.185631
1,Sheep breeding in Central Tunisia: varied stra...,Sheep breeding in central Tunisia remains wide...,0.898033,0.276903,0.103824,0.507857,0.045728,0.022908,0.031643
2,I eat two meals per day impact of climate vari...,Background: Improved understanding of the infl...,0.959514,0.203537,0.073672,0.542869,0.030125,0.014789,0.060198
3,Migration and Self-Protection Against Climate ...,Climate change will affect the livelihoods of ...,0.726716,0.298070,0.074741,0.556097,0.047065,0.041017,0.046210
4,Migration as an adaptive strategy to climate v...,There is increasing consensus that the effects...,0.343252,0.451629,0.112945,0.427338,0.104174,0.090955,0.173812

In [266]:
predictions.to_csv('results/sector_predictions_kf.csv',index=False)

In [267]:
predictions.shape

(1680, 9)